version: '3'

services:
  mariadb_registro:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: registro_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3307:3306"
    volumes:
      - ./data-registro:/var/lib/mysql

  phpmyadmin_registro:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb_registro
      PMA_USER: example_user
      PMA_PASSWORD: example_password
    ports:
      - "8081:80"
    depends_on:
      - mariadb_registro
